apiVersion: apps/v1                  # Kubernetes API 버전 (apps/v1)
kind: Deployment                     # 리소스 유형 (Deployment)
metadata:
  name: nginx-deployment             # Deployment 이름 (nginx-deployment)
spec:
  replicas: 1                        # 파드의 개수 (여기서는 1개 파드를 실행)
  selector:                          # 파드 선택 기준
    matchLabels:
      app: nginx                     # app=nginx 레이블을 가진 파드 선택
  template:                          # 파드 템플릿 정의
    metadata:
      labels:
        app: nginx                   # 파드에 적용할 레이블 (app=nginx)
    spec:
      containers:                    # 파드 내 컨테이너 목록
      - name: nginx                  # 컨테이너 이름 (nginx)
        image: nginx                 # 컨테이너에 사용할 이미지 (nginx, Apache HTTP 서버 이미지)
        ports:
        - containerPort: 80          # 컨테이너에서 노출할 포트 (80번 포트)

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
